
/*

THIS IS SUPPOSED TO BE PRACTICE.

DATA STRUCTURES AND ALGORITHMS. THE ALPHA AND OMEGA OF PROGRAMMING. THE DNA OF SOFTWARE. LOW-LEVEL COLLEGE COURSE.

I SAID, ILL START WITH C++. IVE USED IT A LOT. ILL USE VISUAL STUDIO, WHICH I HAVE NEVER USED BEFORE.

I SAID, IT WILL IMPROVE MY SKILLS.

I SAID, IT SHOULDNT BE TOO HARD.

I HAVE SAID NOTHING SINCE, FOR MY BREATH HAS BEEN USED ONLY FOR LAMENTATION AND REGRETFUL WAILING.

*/

#include <iostream>




int main() {
    std::cout << "Hello World!\n";
}

